version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - COMFY_API_HOST=comfyui
      - COMFY_API_PORT=8188
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../backend/workflows:/app/workflows
    depends_on:
      - comfyui
      - redis

  comfyui:
    build: 
      context: ..
      dockerfile: docker/comfyui.Dockerfile
    ports:
      - "8188:8188"
    volumes:
      - ../ComfyUI/models:/app/models
      - ../ComfyUI/input:/app/input
      - ../ComfyUI/output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../redis-data:/data
    command: redis-server --appendonly yes
