version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    image: comfyui-backend:latest
    ports:
      - "8000:8000"
    environment:
      # ComfyUI Server Configuration
      - COMFY_API_HOST=comfyui
      - COMFY_API_PORT=8188
      # Redis Server Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # S3 Configuration
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-}
      - S3_PREFIX=${S3_PREFIX:-images/}
      - S3_STORAGE_ENABLED=${S3_STORAGE_ENABLED:-false}
      
    volumes:
      - ../backend/workflows:/app/workflows
    depends_on:
      - comfyui
      - redis

  comfyui:
    build: 
      context: ..
      dockerfile: docker/comfyui.Dockerfile
    image: comfyui:latest
    ports:
      - "8188:8188"
    volumes:
      - C:\ComfyUI_windows_portable\ComfyUI\models:/app/models
      - ../ComfyUI/input:/app/input
      - ../ComfyUI/output:/app/output
      - ../ComfyUI/custom_nodes:/app/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../redis-data:/data
    command: redis-server --appendonly yes
